export const AssetID = {
  mushroom: 'mushroom',
  orb: 'orb',
  block: 'block',
  spaceship: 'spaceship',
  pangball: 'pangball',
  snake: 'snake',
  trsi: 'trsi',
  chaos: 'chaos',
  box: 'box',
  platform: 'platform',
  bot: 'bot',
  pineapple: 'pineapple',
  alien: 'alien',
  ship: 'ship',
  atari1: 'atari1',
  atari2: 'atari2',
  starfield: 'starfield',
  mummy: 'mummy',
  seacreatures: 'seacreatures',
  tstrim: 'tstrim',
  disk: 'disk',
  waters: 'waters',
  ball: 'ball',
  monster: 'monster',
  octopus: 'octopus',
  lazur: 'lazur',
  undersea: 'undersea',
  coral: 'coral',
  sky: 'sky',
  phoenixTexture: 'phoenixTexture',
  phoenixMesh: 'phoenixMesh',
  dragonTexture: 'dragonTexture',
  dragonMesh: 'dragonMesh',
  phaser: 'phaser',
  arrows: 'arrows',
  space: 'space',
  lemming: 'lemming',
  shadow: 'shadow',
  diamond: 'diamond',
  button: 'button',
  back: 'back',
  bikkuriman: 'bikkuriman',
  beball: 'beball',
  darkwing_crazy: 'darkwing_crazy',
  kirito: 'kirito',
  asuna: 'asuna',
  pig: 'pig',
  tile: 'tile',

}

export const Animation = {
  run: 'run',
  walk: 'walk',
  swim: 'swim',
  flight: 'flight',
}
