export const AssetID = {
  mushroom: 'mushroom',
  orb: 'orb',
  block: 'block',
  spaceship: 'spaceship',
  pangball: 'pangball',
  snake: 'snake',
  trsi: 'trsi',
  chaos: 'chaos',
  box: 'box',
  platform: 'platform',
  bot: 'bot',
  pineapple: 'pineapple',
  alien: 'alien',
  ship: 'ship',
  atari1: 'atari1',
  atari2: 'atari2',
  starfield: 'starfield',
  mummy: 'mummy',
  seacreatures: 'seacreatures',
  tstrim: 'tstrim',
  disk: 'disk',
  waters: 'waters',
  ball: 'ball',
  monster: 'monster',
  octopus: 'octopus',
}

export const Animation = {
  run: 'run',
  walk: 'walk',
  swim: 'swim',
}
